# timeout
timeout = "1200s"
# your website url
baseURL = 'https://photography.nathanrichard.dev/'
# website title
title = 'nathanrichard'
# don't touch this
disableKinds = ["section", "taxonomy", "term", "home"]
# robots.txt
enableRobotsTXT = true
defaultContentLanguage = 'en'

# theme as module
[module]
replacements = "github.com/Sped0n/bridget/v2 -> bridget"
[[module.imports]]
path = "github.com/Sped0n/bridget/v2" # deploy with git (recommended)  WARN: you should also set `bundled` to true in params.toml !!!