# description of the site (will be placed in meta)
description = "Website to showcase (mostly analog) photographs taken by Nathan Richard"
# use bundled js and css
# * if you want to build the js and css from scratch, set this to false and run `npm install` and `npm run build`
# * tldr: set this to false if you want to develop and edit the js and css
bundled = true

# whether to use favicon resource links
# generate these with https://realfavicongenerator.net
favicon = true
# modern SVG favicon to use in place of older style .png and .ico files
svgFavicon = "/dot.svg"
# fallback png favicon for unsupported browsers
svgFaviconFallback = "/dot.png"

# resize options for dynamic resolution, please refer to https://gohugo.io/content-management/image-processing/#image-processing-options
loResOpt = "800x webp Lanczos q60"
hiResOpt = "2500x webp Lanczos q75"

# page config
[page]
# unified alt text for all images in the page
unifiedAlt = ''

# Site verification code for Google/Bing/Yandex/Pinterest/Baidu
[verification]
google = ""
bing = ""
yandex = ""
pinterest = ""
baidu = ""
so = ""
sogou = ""