# description of the site (will be placed in meta)
description = "shadira is a website to showcase (mostly analogue) photographs taken by Nathan Richard"

# whether to use favicon resource links
favicon = true
# modern SVG favicon to use in place of older style .png and .ico files
svgFavicon = "/favicon.svg"
# fallback png favicon for unsupported browsers
svgFaviconFallback = "/favicon.png"

# resize options for dynamic resolution, please refer to https://gohugo.io/content-management/image-processing/#image-processing-options
loResOpt = "800x webp Lanczos q60"
hiResOpt = "2500x webp Lanczos q75"

# page config
[page]
# unified alt text for all images in the page
unifiedAlt = ''

# Site verification code for Google/Bing/Yandex/Pinterest/Baidu
[verification]
google = ""
bing = ""
yandex = ""
pinterest = ""
baidu = ""
so = ""
sogou = ""